# Use custom format
format = """
[â”Œâ”€${python}| ](bold cyan)${username}@${hostname} [â”‚](bold cyan) ${directory} \
    ${git_branch}${git_commit}${git_status}${git_state}${git_metrics}[|](bold cyan)\
    ${fill} [|â”€](bold cyan) ${time} [â”€](bold cyan)${line_break}\
[â”‚](bold cyan)\
${memory_usage}\
${env_var}\
${custom}\
${sudo}\
${cmd_duration}\
${jobs}\
${battery}\
${line_break}\
${status}\
${shell}\
[â””â”€](bold cyan)${character}"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[fill]
symbol = " "
style = "bold cyan"

[username]
format = "[${user}](${style})"
style_user = "white"
show_always = true

[hostname]
format = "[${ssh_symbol}](bold blue)[${hostname}](white)"
ssh_only = false

[directory]
format = "[${path}](white)[${read_only}](${read_only_style})"
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "â€¦ /"

[time]
format = "[$time](white)"
disabled = false

[python]
format = '[${symbol}\(${virtualenv}\)â”€](cyan)'
symbol = "ğŸ"  # noto-fonts-emoji
version_format = "${raw}"

[sudo]
disabled = false
symbol = "ï›¨ "  # ttf-nerd-fonts-symbols-mono ?
format = "[${symbol}](${style})"

[git_branch]
format = "[â”‚](bold cyan) [${symbol}${branch}(:${remote_name}/${remote_branch}) ](${style})"
symbol = "î‚  "
always_show_remote = true

[git_commit]
tag_disabled = false

[git_metrics]
disabled = false
format = '([+${added}](${added_style}) [-${deleted}](${deleted_style}) )'

[git_status]
format = '(${conflicted}${stashed}${modified}${staged}${untracked}${ahead_behind} )'
ahead = " [${count}â‡¡ ](green)"
behind = " [${count}â‡£ ](red)"
diverged = " [${ahead_count}â‡¡ ](green)[${behind_count}â‡£ ](red)"

